### Broad casting


In [2]:
import numpy as np
a=np.array([0,1,2])
b=np.array([5,5,5])
print("matrix A\n",a)
print("matrix B\n",b)
print("addition\n",a+b)
print("addition\n",a+5)

matrix A
 [0 1 2]
matrix B
 [5 5 5]
addition
 [5 6 7]
addition
 [5 6 7]


In [8]:
import numpy as np
a=np.array([[0,1,2],[4,5,6]])
b=np.array([[5,5,5],[2,3,4]])
print("matrix A\n",a)
print("matrix B\n",b)
print("addition\n",a+b)
print("addition\n",a+5)

matrix A
 [[0 1 2]
 [4 5 6]]
matrix B
 [[5 5 5]
 [2 3 4]]
addition
 [[ 5  6  7]
 [ 6  8 10]]
addition
 [[ 5  6  7]
 [ 9 10 11]]


In [12]:
import numpy as np
a=np.array([[0,1,2],[4,5,6]])
b=np.array([[5,5,5],[2,3,4]])
c=np.array([2,3,4])
print("matrix A\n",a)
print("matrix B\n",b)
print("addition\n",a+b)
print("addition\n",a+5)
print("addition\n",a.shape)

matrix A
 [[0 1 2]
 [4 5 6]]
matrix B
 [[5 5 5]
 [2 3 4]]
addition
 [[ 5  6  7]
 [ 6  8 10]]
addition
 [[ 5  6  7]
 [ 9 10 11]]
addition
 (2, 3)


In [10]:
import numpy as np
M=np.ones((3,3))
print("matrin\n",M)

matrin
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
import numpy as np
M=np.zeros((3,4))
print("matrix\n",M)

matrix
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
import timeit
import numpy
start=timeit.default_timer()
m=numpy.ones((3,4))
print("matrix\n",m)
end=timeit.default_timer()
print(end-start)




matrix
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0.0005917860000863584
